format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/atmosphere/restart_dump.astart
  hashes:
    binhash: b50dec3de8c91f5a2e68b2b1ef4b34b3
    md5: 7ee68d9fc7c990610c1c1aa3d68126f8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/atmosphere/um.res.yaml
  hashes:
    binhash: 0b2043a8a1635d5e5810436a39f6bcf9
    md5: af13600db25d625714699ad090614641
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/coupler/a2i.nc
  hashes:
    binhash: e613ab662b404ba34238da5eda3094f7
    md5: 71467ab6e2beca279c3c587e8ba18f01
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/coupler/i2a.nc
  hashes:
    binhash: 73c900619625d429aff9fafdc65b93af
    md5: 4672f6f20d789bb18802336f44713641
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/coupler/o2i.nc
  hashes:
    binhash: 2f6ef90a36d7d6273ab50a5f133a84aa
    md5: 73478dcb8808df740c735cb4f1f03e5f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ice/cice_in.nml
  hashes:
    binhash: 9bb4b9290cb01d2b98869371a5d83ef6
    md5: 1576287c82da88ffc4752430100f848e
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ice/ice.restart_file
  hashes:
    binhash: 22987a1fa059f8abd34f45a72c44f0f7
    md5: 0057ab7922ac66ad0970c1a64bd853b0
work/ice/RESTART/iced.20150101:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ice/iced.20150101
  hashes:
    binhash: d1ae84eda046070f0af8b14453cdec06
    md5: 4fb75840c4c6fb3c8afdd74ac3c39911
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ice/input_ice.nml
  hashes:
    binhash: 81ada18151dabec8e26233b74b4bdc80
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ice/mice.nc
  hashes:
    binhash: 6dde76a24ac314dad27d5e09947ff0f8
    md5: 81333f08567afd6e351cbf83b6d61109
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 31f48286fc8a12035ab21e1d833d09d8
    md5: 8526ef0ebaf15b4a5dd58b44ff482106
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 364e493c43d0ef959db4dadc54b9bce0
    md5: 32f88f2f738fbb3cde23ee4271fc712e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_age.res.nc
  hashes:
    binhash: 577e7093d8a86b86e61189c48d93eb30
    md5: 502904711ccc322a3c06fedcb4b5cab3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 54f14736ce541046cf8a4ced81df180b
    md5: cda0a9c738180f688daf8b5fb9d542d4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: eb08281abdcbc4c405be019165b1cb07
    md5: 85e00662a7f1e23da53435b74e61d37b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_density.res.nc
  hashes:
    binhash: 75a1994fe19bcece6e046e66c0021abb
    md5: 011517ba6e2ec5937f12989b1181f90f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 66bd16f710357e40a55bcb1562edd77c
    md5: 04c4c71d848c5bf9f8f1aa568ec4c3d8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5a1e7ea8e5e72c52486def65ff058135
    md5: 437fb32fea6ba37b3705a364a31daef5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_neutral.res.nc
  hashes:
    binhash: df52507f844368c4b43257d8abfc397e
    md5: c365fe4034c462a5e79a7ddf0fb6d5ff
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a52b1298c68e658b007b1fa7a036bc54
    md5: ec2579b8260f1e42b2ef78fc2cd72b51
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5ae94df39f405ebe024d099ef768f6b1
    md5: 6ada2d42c633e83e9b92082f7d1fe1ca
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c7fad1e5cf76ca38e52f3a0453322196
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_solo.res
  hashes:
    binhash: a261c9ca87c0785e620df0cd0df61aba
    md5: 9a6fc6e4c9cf14a8b1266a1cf6c87bce
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 365b85a707f985ff04965ba460a6d049
    md5: 8a7108eb598d54fdf9d153b5ec333414
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 14c023b5f8e0a8c2822bf27eec24b1f8
    md5: 779df9bb5c4ce854e54c0f5fb3b1255b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_tracer.res
  hashes:
    binhash: 7aac06d2aeacab17206bc0e0f2d1d3ed
    md5: c7b08e91a58aa9c10fd93fee6913518b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 96edda841f6b5f6178a5e2b42bb26b71
    md5: 72a8e4db7e9e239b4c6d94a041f50b80
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/tfl561/access-esm/archive/esm-esm-ssp585/restart000/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 14d77661fa2e9e0a47c740c044e39431
    md5: fb5a559381abfe5ba12e97f218290b13
